article: https://www.hackster.io/157744/hardwario-iot-kit-smart-fridge-monitor-17e9bd
video: https://www.youtube.com/watch?v=tyyjO0GoyNA
articles:
  - title: HARDWARIO IoT Kit Smart Fridge Monitor
    url: https://www.hackster.io/157744/hardwario-iot-kit-smart-fridge-monitor-17e9bd
    description: Overfreezing you fridge is not good for your food and power saving, with this fridge monitor, you will always know the temperature in there.
    images:
      - url: https://hackster.imgix.net/uploads/attachments/1050365/_t7ejAVROc3.blob?auto=compress%2Cformat&w=900&h=675&fit=min
images:
  - title:
    url: https://github.com/hardwario/website/blob/master/static/kits-images/climate-monitor/main.png
assembly:
  - name: HARDWARIO Climate Module
  - name: HARDWARIO Core Module
  - name: HARDWARIO Mini Battery Module
