article: https://www.hackster.io/157744/hardwario-iot-kit-smart-fridge-monitor-17e9bd
video: https://www.youtube.com/watch?v=tyyjO0GoyNA
images:
  - title:
    url: https://cdn.myshoptet.com/usr/shop.hardwario.com/user/shop/category_portrait/165-2_climate-monitor-kit-a1.jpg?5de56e1c
assembly:
  - name: BigClown Climate Module
  - name: BigClown Core Module
  - name: BigClown Mini Battery Module
